kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tanzu
networking:
  #disableDefaultCNI: true
  # TKC Pod CIDR Default: 100.96.0.0/11
  podSubnet: 10.10.0.0/16
  # TKC Service CIDR Default: 100.64.0.0/13
  serviceSubnet: 20.20.0.0/16
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# https://github.com/kubernetes-sigs/kind/releases
nodes:
- role: control-plane
- role: worker
- role: worker
