apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: core.hphil.tanzu.vmware.com.20220216
spec:
  refName: core.hphil.tanzu.vmware.com
  version: 20220216
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/pichuang/tkg-core
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
