imageInfo:
  imageRepository: projects-stg.registry.vmware.com/tkg
  imagePullPolicy: IfNotPresent
  images:
    tkgPinnipedPostDeployImage:
      imagePath: tkg-pinniped-post-deploy
      tag: v0.4.1_vmware.1
    pinnipedImage:
      imagePath: pinniped
      tag: v0.4.1_vmware.1
    dexImage:
      imagePath: dex
      tag: v2.27.0_vmware.1
infrastructure_provider: vsphere
tkg_cluster_role: workload
custom_cluster_issuer: ""
custom_tls_secret: ""
http_proxy: ""
https_proxy: ""
no_proxy: ""
identity_management_type: null
pinniped:
  cert_duration: 2160h
  cert_renew_before: 360h
  supervisor_svc_endpoint: "https://0.0.0.0:31234"
  supervisor_ca_bundle_data: "ca_bundle_data_of_pinniped_supervisor_svc"
  supervisor_svc_external_ip: "0.0.0.0"
  supervisor_svc_external_dns: null
  upstream_oidc_client_id: ""
  upstream_oidc_client_secret: ""
  upstream_oidc_issuer_url: "https://0.0.0.0:30167"
  upstream_oidc_tls_ca_data: "ca_bundle_data_of_dex_svc"
  upstream_oidc_claims:
    username: ""
    groups: ""
  upstream_oidc_additional_scopes: []
  upstream_oidc_provider_name: DEPRECATED
  image:
    name: DEPRECATED
    tag: DEPRECATED
    repository: DEPRECATED
    pull_policy: DEPRECATED
  post_deploy_job_image:
    name: DEPRECATED
    tag: DEPRECATED
    repository: DEPRECATED
    pull_policy: DEPRECATED
dex:
  app: dex
  create_namespace: true
  namespace: tanzu-system-auth
  organization: vmware
  commonname: tkg-dex
  config:
    frontend:
      theme: tkg
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    expiry:
      signingKeys: 90m
      idTokens: 5m
      authRequests: 90m
      deviceRequests: 5m
    logger:
      level: info
      format: json
    connector: null
    staticClients: []
    issuerPort: "30167"
    oidc:
      CLIENT_ID: null
      CLIENT_SECRET: null
      issuer: null
      clientID: $OIDC_CLIENT_ID
      clientSecret: $OIDC_CLIENT_SECRET
      basicAuthUnsupported: null
      hostedDomains: [DEPRECATED]
      scopes: [DEPRECATED]
      insecureEnableGroups: true
      insecureSkipEmailVerified: false
      getUserInfo: null
      userIDKey: null
      userNameKey: null
      claimMapping:
        email: email
        email_verified: email_verified
        groups: DEPRECATED
    ldap:
      host: null
      insecureNoSSL: false
      startTLS: null
      rootCA: null
      rootCAData: null
      bindDN: null
      bindPW: null
      BIND_PW_ENV_VAR: null
      usernamePrompt: LDAP Username
      insecureSkipVerify: False
      userSearch:
        baseDN: null
        filter: "(objectClass=posixAccount)"
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: givenName
        scope: sub
      groupSearch:
        baseDN: null
        filter: "(objectClass=posixGroup)"
        nameAttr: cn
        scope: sub
        userMatchers: []
    oauth2:
      skipApprovalScreen: true
      responseTypes: []
    storage:
      type: kubernetes
      config:
        inCluster: true
    enablePasswordDB: false
  service:
    name: dexsvc
    type: null
    annotations: {}
  deployment:
    replicas: 1
  certificate:
    duration: 2160h
    renewBefore: 360h
  image:
    name: DEPRECATED
    tag: DEPRECATED
    repository: DEPRECATED
    pullPolicy: DEPRECATED
  dns:
    aws:
      dnsNames: []
      DEX_SVC_LB_HOSTNAME:
    azure:
      dnsNames: []
      DEX_SVC_LB_HOSTNAME:
    vsphere:
      dnsNames: []
      DEX_SVC_LB_HOSTNAME:
      ipAddresses: []
